name: ac_dart
description: AnyCode Dart services and extensions
version: 0.1.0
homepage: https://github.com/anycode/ac_flutter_framework
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cross_file: ^0.3.3+5
  google_maps_flutter: ^2.5.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  logger: ^2.0.2
  logging: ^1.2.0
  media_storage: ^0.0.1
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  ranges:
    #path: ../../../../dart/lib/ranges
    git:
      url: https://github.com/anycode/ranges.dart.git
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
