name: ac_api_client
description: AnyCode Dart API client (HTTP client with cancelable requests)
version: 0.1.5
homepage: https://github.com/anycode/ac_api_client.dart
repository: https://github.com/anycode/ac_api_client.dart
publish_to: https://pub.anycode.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ac_dart:
    hosted: https://pub.anycode.dev
    version: ^0.1.6
  cancellation_token_http: ^2.0.0
  cross_file: ^0.3.4+1
  http_extensions:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  http_extensions_base_url:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  http_extensions_cache:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  http_extensions_headers:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  http_extensions_log:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  http_extensions_retry:
    hosted: https://pub.anycode.dev
    version: ^1.1.2
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mime: ^1.0.5
  oauth2:
    version: ^2.1.2
    hosted: https://pub.anycode.dev

dev_dependencies:
  lints: ^3.0.0
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
