name: ranges
description: Date / Int / Double ranges support for JSON
version: 2.0.0
#homepage: https://www.example.com
#author: edlman <email@example.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: ^0.15.7

dev_dependencies:
  test: ^1.0.0

