name: ranges
description: Date / Int / Double ranges support for JSON
version: 2.1.0
#homepage: https://www.example.com
#author: edlman <email@example.com>

environment:
  sdk: ">=2.2.2 <2.20.0"

dependencies:
  intl: ^0.16.1

dev_dependencies:
  test: ^1.15.7

