name: ranges
description: Date / Int / Double ranges
version: 3.0.1
#homepage: https://www.example.com
#author: edlman <email@example.com>
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.5

